name: lunasea
description: Self-Hosted Controller
version: 10.2.6+1
publish_to: "none"
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  badges: ^3.1.1
  cached_network_image: ^3.2.3
  cloud_firestore: ^5.6.1
  collection: ^1.17.2
  convert: ^3.1.1
  device_preview: ^1.1.0
  dio: ^5.3.2
  easy_localization: ^3.0.2
  encrypt: ^5.0.1
  expandable: ^5.0.1
  file_picker: ^8.1.7
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0
  firebase_storage: ^12.4.0
  fl_chart: ^0.70.1
  flash: ^3.0.5+1
  flutter_cache_manager: ^3.3.1
  flutter_spinkit: ^5.2.0
  go_router: ^14.6.3
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  in_app_purchase: ^3.1.8
  infinite_scroll_pagination: ^4.0.0
  intl: 0.19.0
  json_annotation: ^4.8.1
  modal_bottom_sheet: ^3.0.0-pre
  package_info_plus: ^8.1.2
  path_provider: ^2.1.0
  percent_indicator: ^4.2.3
  quick_actions: ^1.0.5
  retrofit: ^4.0.1
  sentry_flutter: ^8.12.0
  share_plus: ^10.1.3
  shimmer: ^3.0.0
  simple_icons: ^10.1.3
  stack_trace: ^1.11.0
  stash_memory: ^5.0.1
  supercharged: ^2.1.1
  table_calendar: ^3.0.9
  transparent_image: ^2.0.1
  tuple: ^2.0.2
  url_launcher: ^6.1.12
  uuid: ^4.5.1
  wake_on_lan: ^4.1.0
  window_manager: ^0.4.3
  xml: ^6.3.0
dev_dependencies:
  # Generators
  build_runner: ^2.4.6
  environment_config: ^3.1.0
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  retrofit_generator: ^9.1.5
  # Tooling
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.2
  msix: ^3.16.1
  http: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    # System Assets
    - assets/changelog.json
    - assets/changelog_stable.json
    - assets/images/
    - assets/localization/
  fonts:
    - family: LunaBrandIcons
      fonts:
        - asset: assets/LunaBrandIcons.ttf
flutter_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png
  adaptive_icon_background: "#32323E"
  adaptive_icon_foreground: assets/icon/icon_adaptive.png
flutter_native_splash:
  image: assets/images/branding_full.png
  color: "#32323E"
msix_config:
  architecture: x64
  capabilities: internetClientServer,privateNetworkClientServer
  display_name: LunaSea
  enable_at_startup: false
  execution_alias: lunasea
  identity_name: app.lunasea.lunasea
  install_certificate: false
  logo_path: assets\icon\icon_windows.png
  output_name: lunasea-windows-amd64
  store: false
