name: 'All Platforms'

on:
  push:
    branches:
      - 'master'

  workflow_dispatch:
    inputs:
      flavor:
        type: choice
        required: true
        description: 'Build Flavor'
        default: 'internal'
        options: 
        - 'internal'
        - 'alpha'
        - 'beta'

      android:
        type: boolean
        required: true
        description: 'Build for Android'
        default: "true"

      ios:
        type: boolean
        required: true
        description: 'Build for iOS'
        default: "true"

      macos:
        type: boolean
        required: true
        description: 'Build for macOS'
        default: "true"

jobs:
  build_android:
    if: ${{ (github.event.inputs.android || 'true') == 'true' }}
    uses: CometTools/LunaSea/.github/workflows/build_android.yml@master
    with:
      flavor: ${{ github.event.inputs.flavor || 'internal' }}
    secrets:
      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      KEY_JKS: ${{ secrets.KEY_JKS }}
      KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}

  build_ios:
    if: ${{ (github.event.inputs.ios || 'true') == 'true' }}
    uses: CometTools/LunaSea/.github/workflows/build_ios.yml@master
    with:
      flavor: ${{ github.event.inputs.flavor || 'internal' }}
    secrets:
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_ITC_TEAM_ID: ${{ secrets.APPLE_ITC_TEAM_ID }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      GOOGLE_SERVICE_INFO_PLIST: ${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}
      MATCH_KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
      MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_SSH_PRIVATE_KEY: ${{ secrets.MATCH_SSH_PRIVATE_KEY }}

  build_macos:
    if: ${{ (github.event.inputs.macos || 'true') == 'true' }}
    uses: CometTools/LunaSea/.github/workflows/build_macos.yml@master
    with:
      flavor: ${{ github.event.inputs.flavor || 'internal' }}
    secrets:
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_ITC_TEAM_ID: ${{ secrets.APPLE_ITC_TEAM_ID }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      GOOGLE_SERVICE_INFO_PLIST: ${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}
      MATCH_KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
      MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_SSH_PRIVATE_KEY: ${{ secrets.MATCH_SSH_PRIVATE_KEY }}

  deploy_android:
    needs: build_android
    uses: CometTools/LunaSea/.github/workflows/deploy_android.yml@master
    with:
      flavor: ${{ github.event.inputs.flavor || 'internal' }}
    secrets:
      GOOGLE_PLAY_API: ${{ secrets.GOOGLE_PLAY_API }}

  deploy_ios:
    needs: build_ios
    uses: CometTools/LunaSea/.github/workflows/deploy_ios.yml@master
    with:
      flavor: ${{ github.event.inputs.flavor || 'internal' }}
    secrets:
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_ITC_TEAM_ID: ${{ secrets.APPLE_ITC_TEAM_ID }}
      APPLE_STORE_CONNECT_KEY: ${{ secrets.APPLE_STORE_CONNECT_KEY }}
      APPLE_STORE_CONNECT_KEY_FILEPATH: ${{ secrets.APPLE_STORE_CONNECT_KEY_FILEPATH }}
      APPLE_STORE_CONNECT_KEY_ID: ${{ secrets.APPLE_STORE_CONNECT_KEY_ID }}
      APPLE_STORE_CONNECT_ISSUER_ID: ${{ secrets.APPLE_STORE_CONNECT_ISSUER_ID }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

  deploy_macos:
    needs: build_macos
    uses: CometTools/LunaSea/.github/workflows/deploy_macos.yml@master
    with:
      flavor: ${{ github.event.inputs.flavor || 'internal' }}
    secrets:
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_ITC_TEAM_ID: ${{ secrets.APPLE_ITC_TEAM_ID }}
      APPLE_STORE_CONNECT_KEY: ${{ secrets.APPLE_STORE_CONNECT_KEY }}
      APPLE_STORE_CONNECT_KEY_FILEPATH: ${{ secrets.APPLE_STORE_CONNECT_KEY_FILEPATH }}
      APPLE_STORE_CONNECT_KEY_ID: ${{ secrets.APPLE_STORE_CONNECT_KEY_ID }}
      APPLE_STORE_CONNECT_ISSUER_ID: ${{ secrets.APPLE_STORE_CONNECT_ISSUER_ID }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
