name: 'Build Web'

on:
  workflow_call:
    inputs:
      build_number:
        required: true
        type: string

    secrets:
      FIREBASE_OPTIONS:
        required: true

jobs:
  build:
    name: CanvasKit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Core Files
        uses: actions/download-artifact@v3
        with:
          name: core_files

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: ${{ github.sha }}

      - name: Build LunaSea
        run: |
          echo ${{ secrets.FIREBASE_OPTIONS }} | base64 --decode > lib/firebase_options.dart
          flutter pub get
          flutter build web --web-renderer canvaskit --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-canvaskit
          path: ${{ github.workspace }}/build/web
