name: 'Build Windows'

on:
  workflow_call:
    inputs:
      build-number:
        required: true
        type: string

    secrets:
      FIREBASE_TOKEN:
        required: true

jobs:
  build-app-package:
    name: App Package
    runs-on: windows-latest
    steps:
      - name: Setup Environment
        uses: JagandeepBrar/LunaSea/.github/actions/prepare_for_build@master
        with:
          firebase-token: ${{ secrets.FIREBASE_TOKEN }}
          platform: windows

      - name: Build LunaSea
        run: npm run build:windows

      - name: Prepare Artifact
        run: Compress-Archive -path ${{ github.workspace }}\build\windows\runner\Release\* ${{github.workspace}}\output\lunasea-windows-amd64.zip
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-app-package
          path: ${{ github.workspace }}/output
