name: 'Build Linux'

on:
  workflow_call:
    inputs:
      build_number:
        required: true
        type: string

    secrets:
      FIREBASE_OPTIONS:
        required: true
      
jobs:
  build_snap:
    name: Snap
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Core Files
        uses: actions/download-artifact@v3
        with:
          name: core_files

      - name: Prepare Build
        run: echo ${{ secrets.FIREBASE_OPTIONS }} | base64 --decode > lib/firebase_options.dart
      
      - name: Build LunaSea
        uses: snapcore/action-build@v1
        id: build
      
      - name: Prepare Artifact
        run: |
          mkdir -p output
          mv ${{ steps.build.outputs.snap }} ${{ github.workspace }}/output/LunaSea-Linux-amd64.snap

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-snap
          path: ${{ github.workspace }}/output
