name: '[Build] All Platforms'

on:
  workflow_call:
    inputs:
      FLAVOR:
        required: true
        type: string
      VERSION:
        required: true
        type: string

    secrets:
      APPLE_ID:
        required: true
      APPLE_ITC_TEAM_ID:
        required: true
      APPLE_TEAM_ID:
        required: true
      GOOGLE_SERVICE_INFO_PLIST:
        required: true
      GOOGLE_SERVICES_JSON:
        required: true
      KEY_JKS:
        required: true
      KEY_PROPERTIES:
        required: true
      MATCH_KEYCHAIN_NAME:
        required: true
      MATCH_KEYCHAIN_PASSWORD:
        required: true
      MATCH_PASSWORD:
        required: true
      MATCH_SSH_PRIVATE_KEY:
        required: true

jobs:    
  build_android:
    name: Build Android
    uses: CometTools/LunaSea/.github/workflows/build_android.yml@master
    with:
      FLAVOR: ${{ inputs.FLAVOR }}
      VERSION: ${{ inputs.VERSION }}
    secrets:
      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      KEY_JKS: ${{ secrets.KEY_JKS }}
      KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}

  build_ios:
    name: Build iOS
    uses: CometTools/LunaSea/.github/workflows/build_ios.yml@master
    with:
      FLAVOR: ${{ inputs.FLAVOR }}
      VERSION: ${{ inputs.VERSION }}
    secrets:
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_ITC_TEAM_ID: ${{ secrets.APPLE_ITC_TEAM_ID }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      GOOGLE_SERVICE_INFO_PLIST: ${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}
      MATCH_KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
      MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_SSH_PRIVATE_KEY: ${{ secrets.MATCH_SSH_PRIVATE_KEY }}

  build_macos:
    name: Build macOS
    uses: CometTools/LunaSea/.github/workflows/build_macos.yml@master
    with:
      FLAVOR: ${{ inputs.FLAVOR }}
      VERSION: ${{ inputs.VERSION }}
    secrets:
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_ITC_TEAM_ID: ${{ secrets.APPLE_ITC_TEAM_ID }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      GOOGLE_SERVICE_INFO_PLIST: ${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}
      MATCH_KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
      MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_SSH_PRIVATE_KEY: ${{ secrets.MATCH_SSH_PRIVATE_KEY }}
