name: 'Build Web'

on:
  workflow_call:
    inputs:
      build-number:
        required: true
        type: string

    secrets:
      FIREBASE_OPTIONS:
        required: true

jobs:
  build-canvaskit:
    name: CanvasKit
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: JagandeepBrar/LunaSea/.github/actions/prepare_for_build@master
        with:
          platform: web
          firebase-options: ${{ secrets.FIREBASE_OPTIONS }}

      - name: Build LunaSea
        run: flutter build web --web-renderer canvaskit --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-canvaskit
          path: ${{ github.workspace }}/build/web
