name: '[Build] Alpha - iOS'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: 'master'
          fetch-depth: 0
      
      - name: Setup SSH Keys
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.MATCH_SSH_PRIVATE_KEY }}

      - name: Setup Private Keys
        working-directory: ${{ github.workspace }}
        run: |
          echo ${{ secrets.GOOGLE_SERVICE_INFO_PLIST }} | base64 --decode > ios/GoogleService-Info.plist
          echo ${{ secrets.APPLE_STORE_CONNECT_APIKEY }} | base64 --decode > ios/${{ secrets.APPLE_STORE_CONNECT_KEY_FILEPATH }}


      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.5'

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Install Flutter
        uses: subosito/flutter-action@v2.0.3
        with:
          channel: 'beta'

      - name: Prepare Cache
        uses: actions/cache@v2
        with:
          key: pub-${{ hashFiles('pubspec.yaml') }}
          path: |
            ${{ env.PUB_CACHE }}
            ${{ github.workspace }}/ios/Pods
            ${{ github.workspace }}/macos/Pods

      - name: Setup Flutter
        working-directory: ${{ github.workspace }}
        run: |
          flutter pub get

      - name: Install Pods
        working-directory: ${{ github.workspace }}/ios
        run: |
          pod install --repo-update

      - name: Run Fastlane
        working-directory: ${{ github.workspace }}/ios
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
          MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
          APPLE_STORE_CONNECT_KEY_ID: ${{ secrets.APPLE_STORE_CONNECT_KEY_ID }}
          APPLE_STORE_CONNECT_ISSUER_ID: ${{ secrets.APPLE_STORE_CONNECT_ISSUER_ID }}
          APPLE_STORE_CONNECT_KEY_FILEPATH: ${{ secrets.APPLE_STORE_CONNECT_KEY_FILEPATH }}
        run: |
          bundle install
          bundle exec fastlane alpha
