name: 'Build Linux'

on:
  workflow_call:
    inputs:
      build-number:
        required: true
        type: string

    secrets:
      FIREBASE_TOKEN:
        required: true
      
jobs:
  build-snap:
    name: Snap
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: JagandeepBrar/LunaSea/.github/actions/prepare_for_build@master
        with:
          firebase-token: ${{ secrets.FIREBASE_TOKEN }}
          platform: linux
      
      - name: Build LunaSea
        uses: snapcore/action-build@v1
        id: build
      
      - name: Prepare Artifact
        run: mv ${{ steps.build.outputs.snap }} ${{ github.workspace }}/output/LunaSea-Linux-amd64.snap

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-snap
          path: ${{ github.workspace }}/output
