name: '[Deploy] All Platforms'

on:
  workflow_call:
    inputs:
      FLAVOR:
        required: true
        type: string
      VERSION:
        required: true
        type: string
    secrets:
      APPLE_ID:
        required: true
      APPLE_ITC_TEAM_ID:
        required: true
      APPLE_STORE_CONNECT_ISSUER_ID:
        required: true
      APPLE_STORE_CONNECT_KEY:
        required: true
      APPLE_STORE_CONNECT_KEY_FILEPATH:
        required: true
      APPLE_STORE_CONNECT_KEY_ID:
        required: true
      APPLE_TEAM_ID:
        required: true
      GOOGLE_PLAY_API:
        required: true

jobs:
  deploy_android:
    name: Deploy Android
    uses: CometTools/LunaSea/.github/workflows/deploy_android.yml@master
    with:
      FLAVOR: ${{ inputs.FLAVOR }}
      VERSION: ${{ inputs.VERSION }}
    secrets:
      GOOGLE_PLAY_API: ${{ secrets.GOOGLE_PLAY_API }}

  deploy_ios:
    name: Deploy iOS
    uses: CometTools/LunaSea/.github/workflows/deploy_ios.yml@master
    with:
      FLAVOR: ${{ inputs.FLAVOR }}
      VERSION: ${{ inputs.VERSION }}
    secrets:
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_ITC_TEAM_ID: ${{ secrets.APPLE_ITC_TEAM_ID }}
      APPLE_STORE_CONNECT_KEY: ${{ secrets.APPLE_STORE_CONNECT_KEY }}
      APPLE_STORE_CONNECT_KEY_FILEPATH: ${{ secrets.APPLE_STORE_CONNECT_KEY_FILEPATH }}
      APPLE_STORE_CONNECT_KEY_ID: ${{ secrets.APPLE_STORE_CONNECT_KEY_ID }}
      APPLE_STORE_CONNECT_ISSUER_ID: ${{ secrets.APPLE_STORE_CONNECT_ISSUER_ID }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

  deploy_macos:
    name: Deploy macOS
    uses: CometTools/LunaSea/.github/workflows/deploy_macos.yml@master
    with:
      FLAVOR: ${{ inputs.FLAVOR }}
      VERSION: ${{ inputs.VERSION }}
    secrets:
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_ITC_TEAM_ID: ${{ secrets.APPLE_ITC_TEAM_ID }}
      APPLE_STORE_CONNECT_KEY: ${{ secrets.APPLE_STORE_CONNECT_KEY }}
      APPLE_STORE_CONNECT_KEY_FILEPATH: ${{ secrets.APPLE_STORE_CONNECT_KEY_FILEPATH }}
      APPLE_STORE_CONNECT_KEY_ID: ${{ secrets.APPLE_STORE_CONNECT_KEY_ID }}
      APPLE_STORE_CONNECT_ISSUER_ID: ${{ secrets.APPLE_STORE_CONNECT_ISSUER_ID }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
