name: '[Deploy] Android'

on:
  workflow_call:
    secrets:
      FLAVOR:
        required: true
      GOOGLE_PLAY_API:
        required: true
      VERSION:
        required: true

jobs:
  deploy:
    name: 'Deploy to Play Store'
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: 'master'
          fetch-depth: 0

      - name: Download App Bundle Artifact
        uses: actions/download-artifact@v2
        with:
          name: android-${{ secrets.VERSION }}
          path: ${{ github.workspace }}

      - name: Install Secret Keys
        working-directory: ${{ github.workspace }}
        run: |
          echo ${{ secrets.GOOGLE_PLAY_API }} | base64 --decode > .fastlane-android-auth.json

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
  
      - name: Deploy to Google Play Store
        working-directory: ${{ github.workspace }}/android
        env:
          SUPPLY_JSON_KEY: ${{ github.workspace }}/.fastlane-android-auth.json
        run: |
          bundle install
          bundle exec fastlane deploy track:${{ secrets.FLAVOR }} aab:${{ github.workspace }}/app-release.aab version_name:android-${{ secrets.VERSION }}
