name: Prepare

on:
  workflow_call:
    outputs:
      flavor:
        description: "Build Flavor Environment (internal, alpha, beta, production)"
        value: ${{ jobs.flavor.outputs.output1 }}
      track:
        description: "Track Name (Develop, Alpha, Beta, Production)"
        value: ${{ jobs.flavor.outputs.output2 }}

jobs:
  flavor:
    name: Flavor
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.output.outputs.flavor }}
      output2: ${{ steps.output.outputs.track }}
    steps:
      - name: Set Flavor Output
        id: output
        run: |
          echo "::set-output name=flavor::internal"
          echo "::set-output name=track::Develop"

      - name: Create Flavor Configuration
        working-directory: ${{ github.workspace }}
        run: |
          echo $'FLAVOR=${{ steps.flavor.outputs.flavor }}\nCOMMIT=${{ github.sha }}' > .flavor

      - name: Upload Flavor Configuration
        uses: actions/upload-artifact@v2
        with:
          name: flavor-${{ github.sha }}
          path: ${{ github.workspace }}/.flavor
