name: Publish Linux

on:
  workflow_call:
    inputs:
      build-title:
        required: true
        type: string
      flavor:
        required: true
        type: string

    secrets:
      SNAPCRAFT_TOKEN:
        required: true

jobs:
  snapcraft:
    name: Snapcraft
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: JagandeepBrar/LunaSea/.github/actions/prepare_for_deployment@master
        with:
          channel: snapcraft
          snapcraft-token: ${{ secrets.SNAPCRAFT_TOKEN }}

      - name: Download Snap
        uses: actions/download-artifact@v3
        with:
          name: linux-snapcraft
          path: ${{ github.workspace }}/output

      - name: Deploy to Snapcraft
        run: snapcraft upload --release=${{ inputs.flavor }} ${{ github.workspace }}/output/lunasea-linux-amd64.snap
