name: Publish iOS

on:
  workflow_call:
    inputs:
      build-changelog:
        required: true
        type: string
      build-flavor:
        required: true
        type: string

    secrets:
      APPLE_ID:
        required: true
      APPLE_ITC_TEAM_ID:
        required: true
      APPLE_STORE_CONNECT_ISSUER_ID:
        required: true
      APPLE_STORE_CONNECT_KEY:
        required: true
      APPLE_STORE_CONNECT_KEY_ID:
        required: true
      APPLE_TEAM_ID:
        required: true

jobs:
  app-store:
    name: App Store (iOS)
    runs-on: macos-latest
    steps:
      - name: Setup Environment
        uses: JagandeepBrar/LunaSea/.github/actions/prepare_for_deployment@master
        with:
          channel: app-store
          appstore-connect-key: ${{ secrets.APPLE_STORE_CONNECT_KEY }}

      - name: Download App Store Package
        uses: actions/download-artifact@v3
        with:
          name: ios-appstore-package
          path: ${{ github.workspace }}/output

      - name: Generate Changelog
        env:
          CHANGELOG: ${{ inputs.build-changelog }}
          CHANGELOG_PATH: ${{ github.workspace }}/ios/fastlane
        run: |
          mkdir -p $CHANGELOG_PATH
          echo $CHANGELOG > $CHANGELOG_PATH/changelog.txt

      - name: Deploy to App Store Connect
        working-directory: ${{ github.workspace }}/ios
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ITC_TEAM_ID: ${{ secrets.APPLE_ITC_TEAM_ID }}
          APPLE_STORE_CONNECT_ISSUER_ID: ${{ secrets.APPLE_STORE_CONNECT_ISSUER_ID }}
          APPLE_STORE_CONNECT_KEY_FILEPATH: ${{ github.workspace }}/keys/appstore.p8
          APPLE_STORE_CONNECT_KEY_ID: ${{ secrets.APPLE_STORE_CONNECT_KEY_ID }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: bundle exec fastlane deploy_appstore groups:${{ inputs.build-flavor }} ipa:${{ github.workspace }}/output/lunasea-ios.ipa
