name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      flavor:
        description: Build Flavor
        required: true
        default: edge
        type: choice
        options:
          - edge
          - beta
          - candidate
          - stable

jobs:
  cancel:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  prepare_build:
    name: Prepare Build
    needs: [ cancel ]
    uses: JagandeepBrar/LunaSea/.github/workflows/prepare_build.yml@master
    with:
      ref: ${{ github.event.inputs.flavor }}

  prepare_channels:
    name: Prepare Channels
    needs: [ cancel ]
    uses: JagandeepBrar/LunaSea/.github/workflows/prepare_channels.yml@master
    with:
      ref: ${{ github.event.inputs.flavor }}

  generate_files:
    name: Generate
    needs: [ prepare_build ]
    uses: JagandeepBrar/LunaSea/.github/workflows/generate_files.yml@master
    secrets:
      FIREBASE_OPTIONS: ${{ secrets.FIREBASE_OPTIONS }}

  validate:
    name: Validate
    needs: [ generate_files ]
    uses: JagandeepBrar/LunaSea/.github/workflows/validate.yml@master
    secrets:
      FIREBASE_OPTIONS: ${{ secrets.FIREBASE_OPTIONS }}

  android:
    name: Android
    needs: [ prepare_build, prepare_channels, validate ]
    uses: JagandeepBrar/LunaSea/.github/workflows/release_android.yml@master
    with:
      build_flavor: ${{ needs.prepare_build.outputs.build_flavor }}
      build_number: ${{ needs.prepare_build.outputs.build_number }}
      channel: ${{ needs.prepare_channels.outputs.android }}
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      FIREBASE_OPTIONS: ${{ secrets.FIREBASE_OPTIONS }}
      GOOGLE_PLAY_API: ${{ secrets.GOOGLE_PLAY_API }}
      KEY_JKS: ${{ secrets.KEY_JKS }}
      KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}

  ios:
    name: iOS
    needs: [ prepare_build, prepare_channels, validate ]
    uses: JagandeepBrar/LunaSea/.github/workflows/release_ios.yml@master
    with:
      build_flavor: ${{ needs.prepare_build.outputs.build_flavor }}
      build_number: ${{ needs.prepare_build.outputs.build_number }}
      channel: ${{ needs.prepare_channels.outputs.ios }}
    secrets:
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_ITC_TEAM_ID: ${{ secrets.APPLE_ITC_TEAM_ID }}
      APPLE_STORE_CONNECT_ISSUER_ID: ${{ secrets.APPLE_STORE_CONNECT_ISSUER_ID }}
      APPLE_STORE_CONNECT_KEY: ${{ secrets.APPLE_STORE_CONNECT_KEY }}
      APPLE_STORE_CONNECT_KEY_FILEPATH: ${{ secrets.APPLE_STORE_CONNECT_KEY_FILEPATH }}
      APPLE_STORE_CONNECT_KEY_ID: ${{ secrets.APPLE_STORE_CONNECT_KEY_ID }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      FIREBASE_OPTIONS: ${{ secrets.FIREBASE_OPTIONS }}
      MATCH_KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
      MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_SSH_PRIVATE_KEY: ${{ secrets.MATCH_SSH_PRIVATE_KEY }}

  macos:
    name: macOS
    needs: [ prepare_build, prepare_channels, validate ]
    uses: JagandeepBrar/LunaSea/.github/workflows/release_macos.yml@master
    with:
      build_flavor: ${{ needs.prepare_build.outputs.build_flavor }}
      build_number: ${{ needs.prepare_build.outputs.build_number }}
      channel: ${{ needs.prepare_channels.outputs.macos }}
    secrets:
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_ITC_TEAM_ID: ${{ secrets.APPLE_ITC_TEAM_ID }}
      APPLE_STORE_CONNECT_ISSUER_ID: ${{ secrets.APPLE_STORE_CONNECT_ISSUER_ID }}
      APPLE_STORE_CONNECT_KEY: ${{ secrets.APPLE_STORE_CONNECT_KEY }}
      APPLE_STORE_CONNECT_KEY_FILEPATH: ${{ secrets.APPLE_STORE_CONNECT_KEY_FILEPATH }}
      APPLE_STORE_CONNECT_KEY_ID: ${{ secrets.APPLE_STORE_CONNECT_KEY_ID }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      FIREBASE_OPTIONS: ${{ secrets.FIREBASE_OPTIONS }}
      MATCH_KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
      MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_SSH_PRIVATE_KEY: ${{ secrets.MATCH_SSH_PRIVATE_KEY }}

  web:
    name: Web
    needs: [ prepare_build, prepare_channels, validate ]
    if: ${{ needs.prepare.outputs.build_flavor == 'edge' }}
    uses: JagandeepBrar/LunaSea/.github/workflows/release_web.yml@master
    with:
      build_flavor: ${{ needs.prepare_build.outputs.build_flavor }}
      build_number: ${{ needs.prepare_build.outputs.build_number }}
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      FIREBASE_OPTIONS: ${{ secrets.FIREBASE_OPTIONS }}
